import localFont from 'next/font/local'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter, Space_Grotesk } from 'next/font/google'
import '@/lib/styles/theme.css'
import '@/lib/styles/prism.css'
import { cn } from '@/lib/utils'
import { NextThemesProvider } from '@/components/providers/NextThemesProvider'

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-inter'
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-spaceGrotesk'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary: 'primary-gradient',
          footerActionLink: 'primary-text-gradient hover:text-primary-500'
        }
      }}
    >
      <html
        lang='en'
        suppressHydrationWarning
        className={cn(inter.variable, spaceGrotesk.variable)}
      >
        <body>
          <NextThemesProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            storageKey='stackoverflow-theme'
            disableTransitionOnChange
          >
            {children}
          </NextThemesProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
